'use strict';
const $=id=>document.getElementById(id);
$('area-toggle')?.addEventListener('click',()=>{const wrong=$('area-square').classList.toggle('wrong');$('area-toggle').setAttribute('aria-pressed',String(wrong));$('area-toggle').textContent=wrong?'Restore correct area scaling':'Show the misleading 200% scale';$('area-label').innerHTML=wrong?'Misleading scaling<br><b>4× area · 200% per side</b>':'Correct scaling<br><b>2× area · 141% per side</b>';});
let reveal=0;
$('reveal-next')?.addEventListener('click',()=>{reveal=(reveal+1)%3;$('reveal-b').classList.toggle('concealed',reveal<1);$('reveal-insight').classList.toggle('concealed',reveal<2);$('reveal-status').textContent=['1 / 3 · Establish a baseline: Route A takes 24 minutes.','2 / 3 · Introduce the comparison: Route B takes 36 minutes.','3 / 3 · Explain the difference: Route B takes 12 minutes longer.'][reveal];$('reveal-next').textContent=['Reveal the comparison →','Reveal the insight →','Start again ↺'][reveal];});
let cropped=false;
$('baseline-toggle')?.addEventListener('click',()=>{cropped=!cropped;$('baseline-a').style.height=cropped?'120px':'196px';$('baseline-b').style.height='200px';$('baseline-toggle').setAttribute('aria-pressed',String(cropped));$('baseline-toggle').textContent=cropped?'Restore the zero baseline':'Crop the baseline to 95';$('baseline-note').textContent=cropped?'Baseline: 95. Visible lengths are 3 and 5 units. The values remain 98 and 100.':'Baseline: 0. Visible lengths are 98 and 100 units.';});
let elapsed=0,start=0,frame=0,running=false;
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
function paint(ms){$('traveler-a').style.left=Math.min(100,ms/4000*100)+'%';$('traveler-b').style.left=Math.min(100,ms/6000*100)+'%';}
function stop(){if(running)elapsed=Math.min(6000,performance.now()-start);running=false;cancelAnimationFrame(frame);$('route-pause').disabled=true;}
function tick(now){elapsed=Math.min(6000,now-start);paint(elapsed);if(elapsed<6000&&running)frame=requestAnimationFrame(tick);else{running=false;$('route-pause').disabled=true;$('route-play').textContent='Replay comparison';$('route-status').textContent='Both arrived. A: 24 min. B: 36 min. Route B took 12 minutes longer.';}}
$('route-play')?.addEventListener('click',()=>{const wasRunning=running;stop();if(wasRunning||elapsed>=6000)elapsed=0;if(reduced.matches){elapsed=6000;paint(elapsed);$('route-status').textContent='Reduced motion: final comparison shown. A: 24 minutes; B: 36 minutes; difference: 12 minutes.';$('route-play').textContent='Replay comparison';return;}running=true;start=performance.now()-elapsed;$('route-pause').disabled=false;$('route-play').textContent='Restart comparison';$('route-status').textContent='Playing: equal distance, shared clock. 1 playback second = 6 route minutes.';frame=requestAnimationFrame(tick);});
$('route-pause')?.addEventListener('click',()=>{stop();$('route-play').textContent='Resume comparison';$('route-status').textContent='Paused at '+(elapsed/1000).toFixed(1)+' seconds of playback. A takes 24 minutes; B takes 36.';});
$('route-reset')?.addEventListener('click',()=>{stop();elapsed=0;paint(0);$('route-play').textContent='Play comparison';$('route-status').textContent='Route A arrives after 4 seconds of playback. Route B arrives after 6.';});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&running){stop();$('route-play').textContent='Resume comparison';$('route-status').textContent='Playback paused while the page is hidden.';}});
